{% set name = "pywaterflood" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pywaterflood-{{ version }}.tar.gz
  sha256: 3fdb08ac1a5209375aa09b468b3405914d733711797d9efa3d9bfe9cff6426a2

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  number: 1
  skip: true  # [py<37]
  skip: true  # [win and python_impl=="pypy"]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - maturin >=1.2.1,<2                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=0.13
    - pip
  run:
    - python
    - numpy >=1.21
    - scipy >=1.4
    - pandas >=1.3.5
    - openpyxl >=3.0.9
    - joblib >=1.1.0

test:
  imports:
    - pywaterflood
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Physics-inspired waterflood performance modeling
  home: https://pywaterflood.readthedocs.io
  license: BSD-2-Clause
  license_file:
    - THIRDPARTY.yml
    - LICENSE

extra:
  recipe-maintainers:
    - frank1010111
